name: 'Build FreeIOE with toolchains'
description: 'Build a FreeIOE, using the pre-built toolchains'

inputs:
  action:
    description: 'Build action script name'
    required: true
  workdir:
    description: 'Where is the building directory'

outputs:
  filename:
    description: 'Name of the built file'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.action }}
    - ${{ inputs.workdir }}

branding:
  icon: package
  color: gray-dark
