#!/usr/bin/env bash

set -e

WORKDIR=$1
CUR_DIR=`pwd`

if [ -n "$WORKDIR" ]; then
	WORKDIR_NEW=$CUR_DIR/$WORKDIR
else
	WORKDIR_NEW=$CUR_DIR
fi

apt-get update
apt-get install -y python libssl-dev

bash /scripts/build_ext_all.sh ${WORKDIR_NEW} opcua

